### PR TITLE
Small workaround using OMXPlayer

### PR DESCRIPTION
**Pull request by dagwieers**
This is a workaround that improves playback on Raspberry Pi and older  on Kodi v18 and older.

This works on Raspberry Pi, needs to be tested on RPi4 and non-RPi.

This relates to #4

### CODE REVIEW

**Comment by michaelarnauts** [comment]
This doesn't seem to give any issues on my linux x64 install.

Does omxplayer also work if we would switch to Inputstream Adaptive?

**Comment by dagwieers** [comment]
I think so, it did on Retrospect AFAICT.

**Comment by dagwieers** [comment]
It doesn't give issues because even if the option was there, it wouldn't work.

We may want to make this a setting (so the user can influence the behaviour) or provide a notification that we changed this global setting. Maybe set_global_setting should always notify the user when changing settings?

**Comment by michaelarnauts** [comment]
I wouldn't always show a notification, this is annoying when you switch between Netflix (that does the opposite).

A setting to turn this behaviour on could be useful though. Maybe we can even hide this setting in non-rpi devices?

**Comment by michaelarnauts** [comment]
@dagwieers could you rebase on `master` please?

**Comment by dagwieers** [comment]
Done !

**Pull request merged**
