### PR TITLE
Py2/3 compatibility fixes

### PR DESCRIPTION
**Pull request by mediaminister**
While testing the add-on with Kodi 19, I had to fix two Python 3 errors.

### CODE REVIEW

**Comment by dagwieers** [comment]
We should look to add those code paths to unit and/or integration tests.

And I will fix the default Codecov config to target 65%.

**Comment by michaelarnauts** [comment]
I'm actually surprised that the coverage is so low. There are not that much code paths that require credentials.

**Comment by michaelarnauts** [comment]
Oh, I see. It is awsidp that is also taking up some percentages and that is untested on forks.

**Comment by dagwieers** [comment]
Yes, without authentication it is always lower. Unfortunately you cannot tell Codecov to have different diffs and graphs for PRs and for pulls. That would give a much better picture of change.

**Pull request merged**
