### PR TITLE
Add support for Python 3.9

### PR DESCRIPTION
**Pull request by michaelarnauts**
* Run tests with Python 3.9
* Don't run tests on Python 3.5 anymore

### CODE REVIEW

**Comment by dagwieers** [comment]
Python 3.5 may still be around on older Kodi boxes, so I would keep it around for some time.
(I listed this somewhere in a ticket when we implemented a workaround for Python 3.5 because it affected users)

**Comment by mediaminister** [comment]
Python 3.5 is used with OSMC on Debian Stretch: https://github.com/add-ons/plugin.video.vrt.nu/pull/586

**Comment by michaelarnauts** [comment]
Hmm, that's odd. As far as I know, there is no version of OSMC with debian stretch that has Kodi 19 (and thus is using Python 3.5). The beta versions of Kodi 19 all run on debian buster, and they have Python 3.7.

I can add the tests for py35 back since the addon is compatible anyway, i just didn't want to extend the CI time.

**Comment by dagwieers** [comment]
That is up to you. At some point this was the case (and it may still be, albeit not with OSMC).

IMO it is easier to keep it while we still support Python 2.7 anyway. We have one workaround implemented specifically for Python 3.5 too.

Unless we are forced into it again, I prefer to remove all legacy code when we stop supporting Python 2.7. At that point I would also like to rewrite quite a bit using newer idioms, like the f-string.

**Pull request merged**
