### PR TITLE
Fix empty My List due to unknown items

### PR DESCRIPTION
**Pull request by michaelarnauts**
* Ignores unavailable items that are still on My List.
* Use new API endpoint.

### CODE REVIEW

**Comment by michaelarnauts** [comment]
[plugin.video.viervijfzes-0.4.6.zip](https://github.com/add-ons/plugin.video.viervijfzes/files/7996241/plugin.video.viervijfzes-0.4.6.zip)
[plugin.video.viervijfzes-0.4.6+matrix.1.zip](https://github.com/add-ons/plugin.video.viervijfzes/files/7996242/plugin.video.viervijfzes-0.4.6%2Bmatrix.1.zip)

**Comment by michaelarnauts** [comment]
[plugin.video.viervijfzes-0.4.6.zip](https://github.com/add-ons/plugin.video.viervijfzes/files/7996522/plugin.video.viervijfzes-0.4.6.zip)
[plugin.video.viervijfzes-0.4.6+matrix.1.zip](https://github.com/add-ons/plugin.video.viervijfzes/files/7996523/plugin.video.viervijfzes-0.4.6%2Bmatrix.1.zip)

**Comment by badoneti** [comment]
Works fine, all programs listed no HTML in the logs
There were 2 warnings though... posting extract
`2022-02-03 18:21:30.527 T:856      INFO <general>: JSONRPC Server: New connection added
2022-02-03 18:21:33.178 T:827      INFO <general>: CActiveAESink::OpenSink - initialize sink
2022-02-03 18:21:33.178 T:827      INFO <general>: CAESinkALSA::Initialize - Attempting to open device "default"
2022-02-03 18:21:33.190 T:827      INFO <general>: CAESinkALSA::Initialize - Opened device "default"
2022-02-03 18:21:33.192 T:827      INFO <general>: CAESinkALSA::InitializeHW - Your hardware does not support AE_FMT_FLOAT, trying other formats
2022-02-03 18:21:33.192 T:827      INFO <general>: CAESinkALSA::InitializeHW - Using data format AE_FMT_S24NE4
2022-02-03 18:21:36.387 T:821      INFO <general>: Loading skin file: Settings.xml, load type: KEEP_IN_MEMORY
2022-02-03 18:21:49.220 T:821      INFO <general>: Loading skin file: AddonBrowser.xml, load type: KEEP_IN_MEMORY
2022-02-03 18:21:53.106 T:821      INFO <general>: Loading skin file: DialogConfirm.xml, load type: KEEP_IN_MEMORY
2022-02-03 18:21:57.295 T:821      INFO <general>: Loading skin file: SettingsCategory.xml, load type: KEEP_IN_MEMORY
2022-02-03 18:22:13.973 T:821      INFO <general>: Loading skin file: FileBrowser.xml, load type: KEEP_IN_MEMORY
2022-02-03 18:22:31.022 T:848      INFO <general>: CPythonInvoker(4, /storage/.kodi/addons/plugin.video.viervijfzes/service_entry.py): script successfully run
2022-02-03 18:22:31.260 T:848      INFO <general>: Python interpreter interrupted by user
2022-02-03 18:22:31.963 T:882      INFO <general>: CAddonMgr::FindAddon: plugin.video.viervijfzes v0.4.6+matrix.1 installed
2022-02-03 18:22:31.971 T:884      INFO <general>: initializing python engine.
2022-02-03 18:22:32.440 T:821   WARNING <general>: CGUIMediaWindow::OnMessage - updating in progress
2022-02-03 18:22:40.119 T:821      INFO <general>: Loading skin file: MyVideoNav.xml, load type: KEEP_IN_MEMORY
2022-02-03 18:22:42.072 T:891      INFO <general>: initializing python engine.
2022-02-03 18:22:42.910 T:891      INFO <general>: CPythonInvoker(11, /storage/.kodi/addons/plugin.video.viervijfzes/addon_entry.py): script successfully run
2022-02-03 18:22:43.257 T:891      INFO <general>: Python interpreter stopped
2022-02-03 18:22:46.242 T:894      INFO <general>: initializing python engine.
2022-02-03 18:22:48.103 T:894   WARNING <general>: Invalid media type ""
2022-02-03 18:22:48.112 T:894      INFO <general>: Skipped 2 duplicate messages..
2022-02-03 18:22:48.112 T:894      INFO <general>: CPythonInvoker(12, /storage/.kodi/addons/plugin.video.viervijfzes/addon_entry.py): script successfully run
2022-02-03 18:22:48.484 T:894      INFO <general>: Python interpreter stopped
2022-02-03 18:22:54.366 T:898      INFO <general>: initializing python engine.
2022-02-03 18:22:55.214 T:898      INFO <general>: CPythonInvoker(13, /storage/.kodi/addons/plugin.video.viervijfzes/addon_entry.py): script successfully run
2022-02-03 18:22:55.572 T:898      INFO <general>: Python interpreter stopped
`

**Comment by michaelarnauts** [comment]
Good to hear. Those warnings are harmless, I'll look into them later.

**Pull request merged**
