### PR TITLE
Use inputstream.adaptive for playback

### PR DESCRIPTION
**Pull request by michaelarnauts**
Playback streams with Inputstream Adaptive.

Based on https://github.com/add-ons/plugin.video.viervijfzes/commit/8d229d4e8aa61501f57bca9d7ea901900eef8043 from @mediaminister 

Helps #4

### CODE REVIEW

**Comment by dagwieers** [comment]
Don't we want to make this a setting so people (in the future) can enable/disable this?

The use-case here is that in the future maybe IA has a bug which breaks playback, or Kodi fixes the playback. Or in case of ARM, OMXplayer works well, but IA may not, etc.

**Comment by michaelarnauts** [comment]
I don't like to have settings without a known use case. It makes the add-on more complex. If we find a use case where it makes sense to disable this, we could add the setting or try to handle it automatically. For now, what I have tested, the results with Inputstream Adaptive are always better, and it is supported on all recent systems anyway.

I don't think there is a downside to using Inputstream Adaptive with OMXplayer?

**Comment by dagwieers** [comment]
I understand wanting to keep things simple, but having options to keep things working helps in offering a "dependable" solution. Nothing hurts more than not being able to watch what you planned to watch.

The examples I gave were situations we may end up in. Given the fact that IA is updated in a whim without testing, and we have known issues, these are not far-fetched.

I haven't tested IA with OMXplayer yet, but I don't expect issues. Neither would I have expected issues with VIER-VIJF-ZES- streams in general ;-) You decide.

**Comment by mediaminister** [comment]
In case of an emergency, you can always disable InputStream Adaptive in Kodi and HLS streams will still play.

**Comment by dagwieers** [comment]
@mediaminister True, but that also impacts other add-ons. So yeah, suboptimal depending on the exact playback issue.

**Comment by mediaminister** [comment]
I agree, InputStream Adaptive is not really needed to play HLS, so it makes sense to give the user a choice.

**Comment by michaelarnauts** [comment]
Sure, we can make it an option then in the settings where we turn on IA by default.

**Pull request merged**
